name: chall2026-zorvax-blog

services:
  zorvax-blog:
    image: athack-ctf/chall2026-zorvax-blog:latest
    container_name: chall2026-zorvax-blog
    build:
      context: ./source
      dockerfile: Dockerfile
    ports:
      - "53027:8080"
