name: chall2026-zorvax-blog

services:
  pixcavation:
    image: athack-ctf/chall2026-zorvax-blog:latest
    container_name: chall2026-zorvax-blog
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"