#########################################################################################################################
# TODO: REPLACE THE CONTENT OF THIS FILE WITH YOUR OWN.
#########################################################################################################################

services:
  web:
    build: .
    image: chall2026-online-chall
    ports:
      - "2026:2026"
